.makeCrossValidSets <- function(data, valid.times) {
  nrows = nrow(data)
  perm.ind.pos = which(data$cl == 1)
  nrows.pos = length(perm.ind.pos)
  perm.ind.neg = which(data$cl == -1)
  nrows.neg = length(perm.ind.neg)
  if (valid.times > nrows.pos)
    stop(sQuote("cross"), " must not exceed positive or negative set sizes!")
  if (valid.times == 1)
    stop(sQuote("cross"), " must be greater than 1!")
  test.ind.pos = tapply(1:nrows.pos, cut(1:nrows.pos, breaks =  valid.times), function(x)
    perm.ind.pos[x])
  test.ind.neg = tapply(1:nrows.neg, cut(1:nrows.neg, breaks =  valid.times), function(x)
    perm.ind.neg[x])
  test.ind = lapply(1:length(test.ind.pos), function (x)
    c(test.ind.pos[[x]], test.ind.neg[[x]]))
  return(test.ind)
}
